"""Add constraints

Revision ID: 50285f2601cd
Revises: a96fbe0322d6
Create Date: 2026-10-02 22:49:08.669644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50285f2601cd'
down_revision: Union[str, Sequence[str], None] = 'a96fbe0322d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_session_reviewer', ['session_id', 'reviewer_id'])

    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_skill_type', ['user_id', 'skill_id', 'type'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_skill_type', type_='unique')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_session_reviewer', type_='unique')

    # ### end Alembic commands ###
